CREATE TABLE DEPLOY.DEFAULT_PATH (
	ID VARCHAR(20) NOT NULL,
	CATEGORY VARCHAR(200),
	FILE_TYPE VARCHAR(200),
	PATH VARCHAR(200) NOT NULL,
	TYPE CHAR(1) NOT NULL
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;
COMMENT ON COLUMN DEPLOY.DEFAULT_PATH.CATEGORY IS '구분';
COMMENT ON COLUMN DEPLOY.DEFAULT_PATH.FILE_TYPE IS '파일타입';
COMMENT ON COLUMN DEPLOY.DEFAULT_PATH.ID IS '구분아이디';
COMMENT ON COLUMN DEPLOY.DEFAULT_PATH.PATH IS '경로';
COMMENT ON COLUMN DEPLOY.DEFAULT_PATH.TYPE IS '운영/개발구분';

CREATE UNIQUE INDEX DEPLOY.PATH_ID_PK ON DEPLOY.DEFAULT_PATH (
	ID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE DEPLOY.DEFAULT_PATH ADD CONSTRAINT PATH_ID_PK
PRIMARY KEY (
	ID
);